### ISSUE TITLE
Inline styles, less, sass or a combination?

### ISSUE THREAD

**Issue by JonatanSalas** [redux-autoform/redux-autoform-bootstrap-ui#11]
I have looked at some of the less file that are defined for some of the bootstrap-ui components, It seems that we could remove all those files and manage as inline styles.

**Comment by andrerpena** [comment]
@JonatanSalas , inline styles have the advantage of not requiring the user to load any CSS/LESS, but it also has the disadvantage of making it harder for the user to customize styles.

I'm gonna give you one example: **Right now**, there's a person in Thomson Reuters working on a Bootstrap/RAF theme so we can integrate RAF into our products. I mean.. If you remove the LESS files we won't be able to set the variables. How are we building the theme then?

If you have a suggestion, please let me know.

**Comment by JonatanSalas** [comment]
@andrerpena well, material ui for example is built on inline styles, the way they achieve customization is through the usage of context API, they got a MUIThemeProvider which transfer the context to it's children and they take how to customize over a json config

**Comment by andrerpena** [comment]
I see.. Can we leave it as LESS for a while, inside Bootstrap until we find out the best way to customize? I mean, you can use inline styles for the Material UI but please leave Bootstrap as is for a while, unless you show me an example of how to customize without LESS. Is this MUIThemeProvider Material specific?

**Comment by JonatanSalas** [comment]
I'm not going to change nothing! I open this issue to discuss about this and to know a bit of your opinion!

**Comment by JonatanSalas** [comment]
Yes, MUITheme is material-ui specific but we can make use of the logic to abstract a themeProvider for RAF.

**Comment by andrerpena** [comment]
So, I agree on letting LESS styles on Bootstrap for now, and, meanwhile, working on a themeProvider for RAF :+1:

**Comment by JonatanSalas** [comment]
https://github.com/cssinjs/jss this is a good proposal

**Comment by andrerpena** [comment]
This is how I think we should address this.

Bootstrap 3 is based on LESS. Every Bootstrap 3 developer is used to theme BS by tweaking [these variables](http://getbootstrap.com/customize/). Besides, every BS 3 application that doesn't use the default theme **already has set these variables** and the devs would expect that RAF-BS would react accordingly. I mean.. They have these variables set already. They want RAF to just be displayed in respect.

Bootstrap 4 will be based on SaSS. RAF-BS is based on `React-Bootstrap`, which is currently based on BS 3 and they are [working on getting into BS 4](https://github.com/react-bootstrap/react-bootstrap/issues/1187). By the time `React-Bootstrap` gets to 4, we should update RAF-BS to the new `React-Boostrap` which will very likely be based on SaSS.

I have experimented with `Material` and I now understand how `MUITheme` works. I like it. [JSS](https://github.com/cssinjs/jss) which was proposed by @JonatanSalas seems cool as well.

But here is what I think:

Every community has it's own way of dealing with styles. BS 3 uses LESS, BS 4 uses SaSS, Material uses MUITheme. We should not be opinionated in terms of styles. We cannot force a way of dealing with styles down someone's throat just because we like it better. We should have every RAF UI deal with themes exactly as the respective community is used to.

So, for me, it all boils down to:
- RAF-BS keeps being LESS until `React-Boostrap` completes BS 4 support and we migrate. Then RAF-BS starts being SaSS.
- RAF-Material uses the MUITheme.
- Possible new RAF UIs will use whatever that community is used to.

This seems pretty reasonable to me, so, I'm closing this issue. If someone disagrees we can reopen it.

Thank you.
