### ISSUE TITLE
Fix react-bootstrap warnings

### ISSUE THREAD

**Issue by andrerpena** [redux-autoform/redux-autoform-bootstrap-ui#13]
We have to fix it before getting this PR: https://github.com/redux-autoform/redux-autoform/pull/50

**Comment by JonatanSalas** [comment]
If the error is about unknown props we should update directly. This trouble is caused because when using React.createElement or rendering a children, some lib creators pass directly the properties with the spread operator, and the dom node doesnt recognize some props. 

![IMG_20160725_224818.jpg](http://i.imgur.com/l1Mrrcq.jpg)

**Comment by andrerpena** [comment]
Reaaally? Let's accept GreenKeeper then?

**Comment by JonatanSalas** [comment]
Yes.. this is normal, because is more easy to pass the props from the parent to the children directly, instead of destructuring the object props and collect the properties your children need jaja. Let's give a try to bootstrap 0.3.0! If there is a trouble with it, we can revert to the version we are using now.

**Comment by andrerpena** [comment]
Good call but I updated everything and apparently it didn't solve. I'm too tired to debug now

![image](http://i.imgur.com/jA4AOc5.png)

Help wanted... I need to sleep

**Comment by JonatanSalas** [comment]
https://facebook.github.io/react/warnings/unknown-prop.html maybe is the version of React which causes this type of error log.

 I have been working with material-ui and the same error appears to happen, it's a warning from development, but it's not our fault, when you use React under production mode this log dissapears.

**Comment by JonatanSalas** [comment]
We will have to take care too when creating new components to not pass directly to the children its parent properties because they could differ.

**Comment by andrerpena** [comment]
Yes. Because we're getting only 2 to 3 errors specifically for inputs I think, I'll try to fix it to eliminate this damn ugly console window :)

**Comment by JonatanSalas** [comment]
Good! :)

**Comment by JonatanSalas** [comment]
@andrerpena working on this..

**Comment by andrerpena** [comment]
Great! Thank you!

**Comment by JonatanSalas** [comment]
All fixed!! :smile: check PR #25!

**Comment by andrerpena** [comment]
@JonatanSalas You rock little Jony!

**Comment by JonatanSalas** [comment]
@andrerpena We are making this rock!
