### ISSUE TITLE
expressionEvaluator fails when a function is passed in fields

### ISSUE THREAD

**Issue by danigomez** [redux-autoform/redux-autoform-bootstrap-ui#36]
Hello! @andrerpena , it's possible to show or hide fields in a form according another field value?? Or is something that we should add?? :smile:

**Comment by andrerpena** [comment]
This was the first feature that I ever implemented :smile: 

```
{
    name: 'myFieldThatShouldHide',
    type: 'string',
    visible: (m) => m.otherField < 100
}

```

Now, if `otherField` >= 100, `myFieldThatShouldHide` disappears.

**Comment by danigomez** [comment]
Cool!!! :smile:

**Comment by danigomez** [comment]
It seems that we broke something :sob:, in the published demo is working but no in the one that's in the repo....

![untitled](https://cloud.githubusercontent.com/assets/1440399/17822042/342c4860-662b-11e6-8dbe-693bd9a6e262.png)

it's failing here:

``` javascript
switch (typeof expression) {
            case 'function':
                try {
                    if (!_expressionHelper) {
                        _expressionHelper = getExpressionHelper();
                    }

                    let evaluation = expression(data, _expressionHelper);
```

I will take a look at this!

**Comment by andrerpena** [comment]
This error makes sense. Here's why:

When you have metadata as literal, we just pass the literal value. No problem at all.

When you metadata is a function, this function must be evaluated. The evaluation of the function takes 2 parameters: `(m, c) => {}`
- **model**: The model, containing all properties. Example: `m.name`.
- **context**: This is an special object containing **everything** the developer might need inside the function. One of the most important things he might want are the localizers. Why? Because RF saves every field as "string" inside the Redux store. I mean, if you have a decimal field, inside the Redux store, it's always going to be a string. That is, if you need to do any calculation inside your function, you first need to convert that into a double before you can do anything. That's why you need localizers.

History time: There's an issue somewhere to remove the **formato** reference. @JonatanSalas knows about it. **formato** is a legacy library that I created to localize numbers. [It's quite interesting, look at the tests](https://github.com/gearz-lab/formato/blob/master/test/index.js). Later on, I dumped formato in favor of numbro.js. RAF uses numbro em moment as localizers.

Back to the issue: Somehow the localizers stopped being initialized. I'll look into it.

Thanks for reporting.

**Comment by danigomez** [comment]
Hey @andrerpena , who should initialize the localizers??

**Comment by danigomez** [comment]
It seems that was a problem with the redux-autoform-utils version!, i was using a different version in redux-autoform that the one i was using in the bootrap-ui demo, so i update the utils version in autoform and it worked!

**Comment by andrerpena** [comment]
@JonatanSalas Congrats man! I'm sorry I've been away. I'll be back this Thursday!
